/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meenigam_Utils_callNative */

#ifndef _Included_com_meenigam_Utils_callNative
#define _Included_com_meenigam_Utils_callNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meenigam_Utils_callNative
 * Method:    giveVector
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_meenigam_Utils_callNative_giveVector
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
