/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meenigam_Utils_callNative */

#ifndef _Included_com_meenigam_Utils_callNative
#define _Included_com_meenigam_Utils_callNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meenigam_Utils_callNative
 * Method:    sayHello
 * Signature: (Ljava/lang/String;I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_meenigam_Utils_callNative_sayHello
  (JNIEnv *, jobject, jstring, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
